name: Delete Cache

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR Number"
        required: true

jobs:
  cache-delete:
    # Run only on organization branches with PRs
    if: github.event_name == 'workflow_dispatch' ||
      github.event.pull_request.head.repo.full_name ==
      github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - name: Delete cache on PR merged
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            PR_NUMBER=${{ github.event.inputs.pr_number }}
          else
            PR_NUMBER=${{ github.event.pull_request.number }}
          fi
          echo "PR Number: $PR_NUMBER"

          curl -s -L https://api.github.com/repos/Maaassistantarknights/Maaassistantarknights/actions/caches |
          jq -r --arg PR_NUMBER "refs/pull/$PR_NUMBER/merge" '.actions_caches[] | select(.ref == $PR_NUMBER) | .id' |
          while read -r id; do
            echo "Deleting cache with ID: $id"

            curl -L -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/MaaAssistantArknights/MaaAssistantArknights/actions/caches/$id"
          done
